// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_mvW6GVtAcXtkBdLNAwJDUXTrdcGCM20',
    appId: '1:675585400995:web:a01ef82638898293421f16',
    messagingSenderId: '675585400995',
    projectId: 'thibiti-c9667',
    authDomain: 'thibiti-c9667.firebaseapp.com',
    storageBucket: 'thibiti-c9667.appspot.com',
    measurementId: 'G-Z64SP0YCZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYXfW5_uwv8xFKpJH_gLLDJd9ECg_CuyI',
    appId: '1:675585400995:android:886f9e2e573aa2c7421f16',
    messagingSenderId: '675585400995',
    projectId: 'thibiti-c9667',
    storageBucket: 'thibiti-c9667.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_zSXlBypEmnykfdFVvkTp5KkXvl2mE7s',
    appId: '1:675585400995:ios:be16010f22a3a659421f16',
    messagingSenderId: '675585400995',
    projectId: 'thibiti-c9667',
    storageBucket: 'thibiti-c9667.appspot.com',
    iosClientId: '675585400995-nb1mp2b4jp50novg5jeecgcueehtcm82.apps.googleusercontent.com',
    iosBundleId: 'com.safiribytes.thibiti',
  );
}
